name: deploy workflow

on:
  workflow_dispatch:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  plan:
    # The type of runner that the job will run on
    name: Terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform AWS Setup
        uses: ./.github/actions/terraform-aws-setup

      - name: Terraform Plan
        run: terraform plan

  deploy:
    name: Terraform apply
    needs: plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform AWS Setup
        uses: ./.github/actions/terraform-aws-setup

      - name: Deploy to AWS
        run: |
          terraform init
          terraform apply -auto-approve